language: perl
perl:
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
addons:
  postgresql: "9.4"
env:
  - "HARNESS_OPTIONS=j2 TEST_POD=1 TEST_ONLINE=postgresql://postgres@/mojo_pg_test"
install:
  - "cpanm -n Test::Pod Test::Pod::Coverage"
  - "cpanm -n --installdeps ."
before_script:
  - psql -c 'create database mojo_pg_test;' -U postgres
sudo: false
